name: Accessibility & Performance Audit (Labeled)

on:
  pull_request:
    types: 
      - labeled

jobs: 

  Lighthouse-Report-Scheduled:
    if: |
      github.event.label.name == 'run audit'
    runs-on: ubuntu-latest
    name: Accessibility and Performance Audit (Scheduled)

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Audit Step
        id: LHCIAction
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            "${{ secrets.BASE_URL }}"
          uploadArtifacts: true