name: Accessibility & Performance Audit (Scheduled)

#Removed triggers for now

jobs: 

  Lighthouse-Report-Scheduled:
    runs-on: ubuntu-latest
    name: Accessibility and Performance Audit (Scheduled)

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Audit Step
        id: LHCIAction
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            "${{ secrets.BASE_URL }}"
          uploadArtifacts: true
