name: "Run Tests"

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]

jobs:
  test:
    name: Run Test Automation
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.4.1
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright System Dependencies
      run: npx playwright install-deps
    
    - name: Create .env file
      run:  echo "${{ secrets.ENV_FILE }}" > .env
    
    - name: Run tests
      run: npx playwright test