name: Run Tests
on: [push]

jobs:

runs-on: ubuntu-latest
steps:
 - name: Check out source code
   uses: actions/checkout@v2
   with:
     feth-depth: 1

 - name: Set up node
   uses: actions/setup-node@v1

 - name: Create .env file
   run:  echo "${{ secrets.ENV_FILE }}" > .env

 - name: Install dependencies
   run: npm ci

 - name: Run tests
   run: npx playwright test