name: Run Tests
on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]

jobs:

runs-on: ubuntu-latest
steps:

- name: Setup Node.js environment
  uses: actions/setup-node@v3.4.1

- name: Create .env file
  run:  echo "${{ secrets.ENV_FILE }}" > .env

- name: Install other ependencies
  run: npm ci
  
- name: Install Playwright System Dependencies
  run: npx playwright install-deps

- name: Run tests
  run: npx playwright test