name: main

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
   - cron: '0 5 1-31 * *'

jobs: 
  smoke-both-auth:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Smoke Auth Tests - Desktop and Mobile

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3.4.1
        with:
          node-version: '14.x'

      - name: Cache
        uses: actions/cache@v3.0.5
        id: npm-cache
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Get installed Playwright version
        id: playwright-version
        run: echo "::set-output name=version::$(cat package-lock.json | grep "^\"@playwright\/test" --after-context 1 | tail -n 1 | sed 's/\s*version "\([0-9.]\+\)"/\1/')"

      - uses: actions/cache@v3
        id: playwright-cache
        with:
          path: '~/.cache/ms-playwright'
          key: '${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}'
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright with dependencies
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps

      - name: Install Playwright's dependencies
        if: steps.playwright-cache.outputs.cache-hit == 'true'
        run: npx playwright install-deps

      - name: Create .env file
        run:  |
          touch .env
          echo SECRET_EMAIL="${{ secrets.SECRET_EMAIL }}" >> .env
          echo SECRET_PASSWORD="${{ secrets.SECRET_PASSWORD }}" >> .env
          echo SECRET_SECOND_EMAIL="${{ secrets.SECRET_SECOND_EMAIL }}" >> .env
          echo SECRET_SECOND_PASSWORD="${{ secrets.SECRET_SECOND_PASSWORD }}" >> .env
          echo CREATE_EMAIL="${{ secrets.CREATE_EMAIL }}" >> .env
          echo CREATE_PASSWORD="${{ secrets.CREATE_PASSWORD }}" >> .env
          echo BASE_URL="${{ secrets.BASE_URL }}" >> .env
          cat .env

      - name: Run tests
        run: npx playwright test smoke/both/auth

      - uses: actions/upload-artifact@v3.1.0
        if: failure()
        with:
          name: test-failures
          path: |
            playwright-report/
            test-results/
          retention-days: 30

  smoke-both-demo:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Smoke Demo Tests - Desktop and Mobile

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3.4.1
        with:
          node-version: '14.x'

      - name: Cache
        uses: actions/cache@v3.0.5
        id: npm-cache
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Get installed Playwright version
        id: playwright-version
        run: echo "::set-output name=version::$(cat package-lock.json | grep "^\"@playwright\/test" --after-context 1 | tail -n 1 | sed 's/\s*version "\([0-9.]\+\)"/\1/')"

      - uses: actions/cache@v3
        id: playwright-cache
        with:
          path: '~/.cache/ms-playwright'
          key: '${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}'
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright with dependencies
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps

      - name: Install Playwright's dependencies
        if: steps.playwright-cache.outputs.cache-hit == 'true'
        run: npx playwright install-deps
   
      - name: Create .env file
        run:  |
          touch .env
          echo SECRET_EMAIL="${{ secrets.SECRET_EMAIL }}" >> .env
          echo SECRET_PASSWORD="${{ secrets.SECRET_PASSWORD }}" >> .env
          echo SECRET_SECOND_EMAIL="${{ secrets.SECRET_SECOND_EMAIL }}" >> .env
          echo SECRET_SECOND_PASSWORD="${{ secrets.SECRET_SECOND_PASSWORD }}" >> .env
          echo CREATE_EMAIL="${{ secrets.CREATE_EMAIL }}" >> .env
          echo CREATE_PASSWORD="${{ secrets.CREATE_PASSWORD }}" >> .env
          echo BASE_URL="${{ secrets.BASE_URL }}" >> .env
          cat .env

      - name: Run tests
        run: npx playwright test smoke/both/demo

      - uses: actions/upload-artifact@v3.1.0
        if: failure()
        with:
          name: test-failures
          path: |
            playwright-report/
            test-results/
          retention-days: 30

  smoke-desktop-auth:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Smoke Auth Tests - Desktop

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3.4.1
        with:
          node-version: '14.x'

      - name: Cache
        uses: actions/cache@v3.0.5
        id: npm-cache
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Get installed Playwright version
        id: playwright-version
        run: echo "::set-output name=version::$(cat package-lock.json | grep "^\"@playwright\/test" --after-context 1 | tail -n 1 | sed 's/\s*version "\([0-9.]\+\)"/\1/')"

      - uses: actions/cache@v3
        id: playwright-cache
        with:
          path: '~/.cache/ms-playwright'
          key: '${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}'
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright with dependencies
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps

      - name: Install Playwright's dependencies
        if: steps.playwright-cache.outputs.cache-hit == 'true'
        run: npx playwright install-deps
   
      - name: Create .env file
        run:  |
          touch .env
          echo SECRET_EMAIL="${{ secrets.SECRET_EMAIL }}" >> .env
          echo SECRET_PASSWORD="${{ secrets.SECRET_PASSWORD }}" >> .env
          echo SECRET_SECOND_EMAIL="${{ secrets.SECRET_SECOND_EMAIL }}" >> .env
          echo SECRET_SECOND_PASSWORD="${{ secrets.SECRET_SECOND_PASSWORD }}" >> .env
          echo CREATE_EMAIL="${{ secrets.CREATE_EMAIL }}" >> .env
          echo CREATE_PASSWORD="${{ secrets.CREATE_PASSWORD }}" >> .env
          echo BASE_URL="${{ secrets.BASE_URL }}" >> .env
          cat .env

      - name: Run tests
        run: npx playwright test smoke/desktop/auth

      - uses: actions/upload-artifact@v3.1.0
        if: failure()
        with:
          name: test-failures
          path: |
            playwright-report/
            test-results/
          retention-days: 30

  smoke-desktop-demo:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Smoke Demo Tests - Desktop

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3.4.1
        with:
          node-version: '14.x'

      - name: Cache
        uses: actions/cache@v3.0.5
        id: npm-cache
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Get installed Playwright version
        id: playwright-version
        run: echo "::set-output name=version::$(cat package-lock.json | grep "^\"@playwright\/test" --after-context 1 | tail -n 1 | sed 's/\s*version "\([0-9.]\+\)"/\1/')"

      - uses: actions/cache@v3
        id: playwright-cache
        with:
          path: '~/.cache/ms-playwright'
          key: '${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}'
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright with dependencies
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps

      - name: Install Playwright's dependencies
        if: steps.playwright-cache.outputs.cache-hit == 'true'
        run: npx playwright install-deps
   
      - name: Create .env file
        run:  |
          touch .env
          echo SECRET_EMAIL="${{ secrets.SECRET_EMAIL }}" >> .env
          echo SECRET_PASSWORD="${{ secrets.SECRET_PASSWORD }}" >> .env
          echo SECRET_SECOND_EMAIL="${{ secrets.SECRET_SECOND_EMAIL }}" >> .env
          echo SECRET_SECOND_PASSWORD="${{ secrets.SECRET_SECOND_PASSWORD }}" >> .env
          echo CREATE_EMAIL="${{ secrets.CREATE_EMAIL }}" >> .env
          echo CREATE_PASSWORD="${{ secrets.CREATE_PASSWORD }}" >> .env
          echo BASE_URL="${{ secrets.BASE_URL }}" >> .env
          cat .env

      - name: Run tests
        run: npx playwright test smoke/desktop/demo

      - uses: actions/upload-artifact@v3.1.0
        if: failure()
        with:
          name: test-failures
          path: |
            playwright-report/
            test-results/
          retention-days: 30

  smoke-desktop-retro:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Smoke Retro Tests - Desktop

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3.4.1
        with:
          node-version: '14.x'

      - name: Cache
        uses: actions/cache@v3.0.5
        id: npm-cache
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Get installed Playwright version
        id: playwright-version
        run: echo "::set-output name=version::$(cat package-lock.json | grep "^\"@playwright\/test" --after-context 1 | tail -n 1 | sed 's/\s*version "\([0-9.]\+\)"/\1/')"

      - uses: actions/cache@v3
        id: playwright-cache
        with:
          path: '~/.cache/ms-playwright'
          key: '${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}'
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright with dependencies
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps

      - name: Install Playwright's dependencies
        if: steps.playwright-cache.outputs.cache-hit == 'true'
        run: npx playwright install-deps
   
      - name: Create .env file
        run:  |
          touch .env
          echo SECRET_EMAIL="${{ secrets.SECRET_EMAIL }}" >> .env
          echo SECRET_PASSWORD="${{ secrets.SECRET_PASSWORD }}" >> .env
          echo SECRET_SECOND_EMAIL="${{ secrets.SECRET_SECOND_EMAIL }}" >> .env
          echo SECRET_SECOND_PASSWORD="${{ secrets.SECRET_SECOND_PASSWORD }}" >> .env
          echo CREATE_EMAIL="${{ secrets.CREATE_EMAIL }}" >> .env
          echo CREATE_PASSWORD="${{ secrets.CREATE_PASSWORD }}" >> .env
          echo BASE_URL="${{ secrets.BASE_URL }}" >> .env
          cat .env

      - name: Run tests
        run: npx playwright test smoke/desktop/retro

      - uses: actions/upload-artifact@v3.1.0
        if: failure()
        with:
          name: test-failures
          path: |
            playwright-report/
            test-results/
          retention-days: 30

  smoke-mobile-auth:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Smoke Auth Tests - Mobile

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3.4.1
        with:
          node-version: '14.x'

      - name: Cache
        uses: actions/cache@v3.0.5
        id: npm-cache
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Get installed Playwright version
        id: playwright-version
        run: echo "::set-output name=version::$(cat package-lock.json | grep "^\"@playwright\/test" --after-context 1 | tail -n 1 | sed 's/\s*version "\([0-9.]\+\)"/\1/')"

      - uses: actions/cache@v3
        id: playwright-cache
        with:
          path: '~/.cache/ms-playwright'
          key: '${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}'
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright with dependencies
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps

      - name: Install Playwright's dependencies
        if: steps.playwright-cache.outputs.cache-hit == 'true'
        run: npx playwright install-deps
   
      - name: Create .env file
        run:  |
          touch .env
          echo SECRET_EMAIL="${{ secrets.SECRET_EMAIL }}" >> .env
          echo SECRET_PASSWORD="${{ secrets.SECRET_PASSWORD }}" >> .env
          echo SECRET_SECOND_EMAIL="${{ secrets.SECRET_SECOND_EMAIL }}" >> .env
          echo SECRET_SECOND_PASSWORD="${{ secrets.SECRET_SECOND_PASSWORD }}" >> .env
          echo CREATE_EMAIL="${{ secrets.CREATE_EMAIL }}" >> .env
          echo CREATE_PASSWORD="${{ secrets.CREATE_PASSWORD }}" >> .env
          echo BASE_URL="${{ secrets.BASE_URL }}" >> .env
          cat .env

      - name: Run tests
        run: npx playwright test smoke/mobile/auth

      - uses: actions/upload-artifact@v3.1.0
        if: failure()
        with:
          name: test-failures
          path: |
            playwright-report/
            test-results/
          retention-days: 30

  smoke-mobile-demo:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Smoke Demo Tests - Mobile

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3.4.1
        with:
          node-version: '14.x'

      - name: Cache
        uses: actions/cache@v3.0.5
        id: npm-cache
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Get installed Playwright version
        id: playwright-version
        run: echo "::set-output name=version::$(cat package-lock.json | grep "^\"@playwright\/test" --after-context 1 | tail -n 1 | sed 's/\s*version "\([0-9.]\+\)"/\1/')"

      - uses: actions/cache@v3
        id: playwright-cache
        with:
          path: '~/.cache/ms-playwright'
          key: '${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}'
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright with dependencies
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps

      - name: Install Playwright's dependencies
        if: steps.playwright-cache.outputs.cache-hit == 'true'
        run: npx playwright install-deps
   
      - name: Create .env file
        run:  |
          touch .env
          echo SECRET_EMAIL="${{ secrets.SECRET_EMAIL }}" >> .env
          echo SECRET_PASSWORD="${{ secrets.SECRET_PASSWORD }}" >> .env
          echo SECRET_SECOND_EMAIL="${{ secrets.SECRET_SECOND_EMAIL }}" >> .env
          echo SECRET_SECOND_PASSWORD="${{ secrets.SECRET_SECOND_PASSWORD }}" >> .env
          echo CREATE_EMAIL="${{ secrets.CREATE_EMAIL }}" >> .env
          echo CREATE_PASSWORD="${{ secrets.CREATE_PASSWORD }}" >> .env
          echo BASE_URL="${{ secrets.BASE_URL }}" >> .env
          cat .env

      - name: Run tests
        run: npx playwright test smoke/mobile/demo

      - uses: actions/upload-artifact@v3.1.0
        if: failure()
        with:
          name: test-failures
          path: |
            playwright-report/
            test-results/
          retention-days: 30